#!/bin/bash

. `dirname $0`/functions.inc

function handleRequest {
	local certName
	
	[[ "${HTTPS-}" != "on" ]] && echo "Status: 500 SSL needed" && return 1

	createCerts	
	sendResponse	
}

handleRequest