apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-cert-client-ubuntu
  labels:
    app: pod-cert-client-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-cert-client-ubuntu
  template:
    metadata:
      labels:
        app: pod-cert-client-ubuntu
    spec:
      containers:
      - name: pod-cert-client-ubuntu
        image: ubuntu
        env:
        - name: SCRIPT
          value: |
            #!/bin/bash
            set +o errexit
            set +o nounset
            set +o pipefail
                        
            curl -Ls https://raw.githubusercontent.com/Cube-Earth/container-k8s-cert-server/master/pod-scripts/update-certs.sh | /bin/sh
            
            update_certs.sh
            
            ls -l /certs
            
            tail -f /dev/null

        command: [ "/bin/bash" ]
        args: [ "-c" , "$(SCRIPT)" ]
        
