apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-cert-client-alpine
  labels:
    app: pod-cert-client-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-cert-client-alpine
  template:
    metadata:
      annotations:
        ssl-cert.server  : "server:cert-test,test-*.test"
        ssl-cert.default : "server:cert-test2"
        ssl-cert.tiller.default: "shared"
        pwd.shared: "spinnaker"
      labels:
        app: pod-cert-client-alpine
    spec:
      containers:
      - name: pod-cert-client-alpine
        image: alpine
        env:
        - name: SCRIPT
          value: |
            #!/bin/sh
            set +o errexit
            set +o nounset
            set +o pipefail
            
            curl -Ls https://raw.githubusercontent.com/Cube-Earth/container-k8s-cert-server/master/pod-scripts/update-certs.sh | /bin/sh
            
            update_certs.sh
            
            ls -l /certs
            
            curl https://pod-cert-server/pwd/a
            curl https://pod-cert-server/pwd/spinnaker
            
            tail -f /dev/null

        command: [ "/bin/sh" ]
        args: [ "-c" , "$(SCRIPT)" ]
